# Generated by Django 4.2.19 on 2025-02-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_category_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='notifications_enabled',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='subscribed_categories',
        ),
    ]
