services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
    depends_on:
      - redis

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume:
  media_volume:
